[tool.poetry]
name = "aws-saa-c03"
version = "0.1.0"
description = ""
authors = ["AriHenrique <arihenriqueuna@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
